### ISSUE TITLE
Doesn't apply to classes ?

### ISSUE THREAD

**Issue by raphaelgoetter** [purifycss/gulp-purifycss#13]
Hello and thank you for this contrib.

I tried gulp-purifycss with some classes that where _not_ present in my HTML page : 

``` css
.kiwi {
    display: block;
}
.banane {
    display: inline;
}
p.kiwi {
    font-weight: bold;
}
p.banane {
    font-weight: normal;
}
```

But all these unused classes where kept in the compiled CSS :(
